name: Fetch GitHub Open Data Metadata

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '2 20 * * *'  # Adjusted cron to run at 21:55 Berlin time (19:55 UTC)

jobs:
  fetch_and_save:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas python-dateutil

      - name: Run GitHub Fetch Script
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          python fetch_github_metadata.py
        # Update the working directory if needed
        working-directory: ${{ github.workspace }}/Downloads

        

      - name: Commit and push changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Update GitHub data" || echo "No changes to commit"
          git push
