name: Fetch Metadata

on:
  schedule:
    # Runs every day at 5:00 am
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  fetch_and_save:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas python-dateutil numpy

    - name: Run Zenodo Fetch Script
      run: |
        python fetch_zenodo_metadata.py
      working-directory: ${{ github.workspace }}/OpenData_metadata

    - name: Run GitHub Fetch Script
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        python fetch_github_metadata.py
      working-directory: ${{ github.workspace }}/OpenData_metadata

    - name: Commit and push changes
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        git commit -m "Update data" || echo "No changes to commit"
        git push
