name: Fetch Zenodo Data

on:
  schedule:
    # Runs every day at midnight
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch_and_save:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas python-dateutil

    - name: Run Zenodo Fetch Script
      run: |
        python Downloads/fetch_zenodo_metadata.py
      working-directory: ${{ github.workspace }}

    - name: Commit and push changes
      run: |
    	  git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Actions"
        git add -A
        git commit -m "Update Zenodo data" || echo "No changes to commit"
        git push
